mod camera;
mod camera_compute;
mod camera_iterator;
mod light;
mod ray;
mod world;
mod intersection_compute;
mod world_iterator;
pub use camera::Camera;
pub use camera_compute::CameraCompute;
pub use camera_iterator::CameraIterator;
pub use light::Light;
pub use ray::{Intersection, SortByTime, Ray};
pub use world::World;
use world::colour_at_ray;
pub use intersection_compute::IntersectionCompute;
pub use world_iterator::WorldIterator;
